- id: A001a
  alias: Turn on light when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: +00:30:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.prise4
  - service: homeassistant.turn_on
    entity_id: light.lightstrip
- id: A001b
  alias: Turn off light after we go to bed
  trigger:
    platform: time
    at: '23:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.prise4
  - service: homeassistant.turn_off
    entity_id: light.lightstrip
  - service: homeassistant.turn_off
    entity_id: switch.prise4
# - id: A002a
#   alias: Turn on lights evy before bed
#   trigger:
#     platform: time
#     at: '20:00:00'
#   action:
#   - service: homeassistant.turn_on
#     entity_id: switch.prise3
# - id: A002b
#   alias: Turn off lights evy in the morning
#   trigger:
#     platform: time
#     at: 07:00:00
#   action:
#   - service: homeassistant.turn_off
#     entity_id: switch.prise3
#   - service: homeassistant.turn_off
#     entity_id: switch.prise3
- id: A003a
  alias: Sensor Info Week
  trigger:
    platform: time
    at: 07:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: homeassistant.turn_on
    entity_id: script.netatmo
- id: A003b
  alias: Sensor Info Weekend
  trigger:
    platform: time
    at: 08:35:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: homeassistant.turn_on
    entity_id: script.netatmo
- id: A004
  alias: Turn off Home Cinema in the evening
  trigger:
    platform: time
    at: '23:59:59'
  action:
  - service: homeassistant.turn_off
    entity_id: script.everything
- id: A005a
  alias: Mettre la table
  trigger:
    platform: time
    at: '18:55:00'
  action:
  - service: homeassistant.turn_on
    entity_id: script.table_up
- id: A005b
  alias: Debarasser la table
  trigger:
    platform: time
    at: '19:55:00'
  action:
  - service: homeassistant.turn_on
    entity_id: script.table_down
- id: A005c
  alias: A qui le tour le week end
  trigger:
    platform: time
    at: 08:30:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: homeassistant.turn_on
    entity_id: script.table_up
- id: A006
  alias: Sortir la poubelle
  trigger:
    platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - thu
  action:
  - service: homeassistant.turn_on
    entity_id: script.garbage
- id: A007
  alias: Fatima
  trigger:
    platform: time
    at: 08:10:00
  condition:
  - condition: time
    weekday:
    - mon
  action:
  - service: homeassistant.turn_on
    entity_id: script.cleaning
- id: A008
  alias: Doorbell Ding
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_porte_de_devant_ding
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: script.doorbell
# Activated when one of the sensors are opened and alarm is armed
- id: A009a
  alias: Windows Alarm
  trigger:
  - entity_id: group.windows
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
# Activated when alarm is trigerred
- id: A009b
  alias: Send notification when alarm triggered
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: 'triggered'
  action:
  - service: script.alarm_on
# Activated when alarm is armed
#- id: A009c
#  alias: indicator alarm is armed away
#  trigger:
#  - entity_id: alarm_control_panel.home_alarm
#    platform: state
#    from: 'disarmed'
#    to: 'pending'
#  action:
#  - service: script.alarm_armed
# Activated when alarm is disarmed
# - id: A009d
#   alias: restore alarm to initial state
#   trigger:
#   - entity_id: alarm_control_panel.home_alarm
#     platform: state
#     to: 'disarmed'
#   action:
#   - service: homeassistant.turn_on
#     entity_id: script.alarm_off
# Activated when smoke is detected
- id: A010
  alias: Send notification on fire alarm
  initial_state: 'off'
  trigger:
  - entity_id: group.smoke
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: script.smoke_alarm
# Activated by parent switch right
- id: A011
  alias: Toggle Light in parents room
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d000237bae7
      click_type: single
  # - event_data:
  #     click_type: single
  #     entity_id: binary_sensor.wall_switch_right_158d000237bae7
  #   event_type: click
  #   platform: event
  # condition: []
  action:
  - service: homeassistant.toggle
    data:
      entity_id: group.spots
# Activated by parent switch left
- id: A012
  alias: Toggle Alarm
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000237bae7
      click_type: single
  # - event_data:
  #     click_type: single
  #     entity_id: binary_sensor.wall_switch_left_158d000237bae7
  #   event_type: click
  #   platform: event
  # condition: []
  action:
  - service: homeassistant.toggle
    data:
      entity_id: switch.alarm_arm_away
# Turn on prise3
- id: A013a
  alias: Turn on prise3
  trigger:
    platform: time
    at: "22:30:00"
  action:
  - service: timer.start
    entity_id: timer.charge
  - service: homeassistant.turn_on
    entity_id: switch.prise3
  - service: homeassistant.turn_on
    entity_id: switch.prise3
# Turn off prise3 at the end of timer
- id: A013b
  alias: Turn off prise3 when end timer
  trigger: 
  - platform: event
    event_type: timer.finished
    event_data: 
      entity_id: timer.charge
  action:
  - service: homeassistant.turn_off
    entity_id: switch.prise3
# Activated when the door is opened
- id: A014
  alias: Door Alert
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002c9c949 
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: script.door_alert
# Activated at night
- id: A015a
  alias: Activate Night Mode
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: Night
# Activated in morning
- id: A015b
  alias: Activate active Mode
  trigger:
    platform: time
    at: "06:30:00"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: Day
# Actions when in Night Mode
- id: A016a
  alias: Activate Night Mode
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: 'Night'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.alarm_arm_home
# Actions when in Day Mode
- id: A016b
  alias: Send notification when alarm triggered
  trigger:
  - entity_id: input_select.home_mode
    platform: state
    to: 'Day'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.alarm_arm_home
