########### DEFAULT CONFIG ########### 
homeassistant:
  packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation
  unit_system: metric
  time_zone: Europe/Brussels
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  whitelist_external_dirs:
    - /config

http:
  base_url: !secret http_base_url
  # ip_ban_enabled: True
  login_attempts_threshold: 3
  # cors_allowed_origins:
  #   - https://google.com
  #   - https://home-assistant.io
  # use_x_forwarded_for: True
  # trusted_networks:
  #   - !secret trusted_ip
  #   - !secret trusted_ip_2

browser_mod:
config:
conversation:
discovery:
# frontend:
#   themes: !include_dir_merge_named themes
history:
logbook:
sun:
system_health:
updater:
map:
mobile_app:
ssdp:
zeroconf:

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

logger:
  default: warn
  logs:
    custom_components.hacs: debug
    homeassistant.components.withings: critical
#    homeassistant.components.netatmo: debug

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 15
  include:
    entities:
      - group.windows
      - group.doors
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
      - group
      - scene
      - script
    entities:
      - sun.sun

########### PLATFORMS ########### 

#light:
#  - platform: hue
#    host: !secret hue_host
#  - platform: xiaomi_miio
#    name: Xiaomi Philips E14
#    host: !secret philips_e14_host
#    token: !secret philips_e14_token
#    model: philips.light.candle

dialogflow:

tts:
  - platform: google_translate
    language: 'fr'
    service_name: google_say
    base_url: !secret tts_base_url

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

# curl -X GET https://api.telegram.org/botYOUR_API_TOKEN/getUpdates
# telegram_bot:
#   - platform: polling
#     api_key: !secret telegram_api_key
#     parse_mode: html
#     allowed_chat_ids:
#       - !secret telegram_chat_id_ju
#       - !secret telegram_chat_id_mo

notify:
  # - name: ju
  #   platform: telegram
  #   chat_id: !secret telegram_chat_id_ju
  # - name: mo
  #   platform: telegram
  #   chat_id: !secret telegram_chat_id_mo
  - name: signal
    platform: rest
    resource: !secret signal_url 
    method: POST_JSON
  # - name: Google Assistant
  #   platform: rest
  #   resource: !secret google_msg_urlnotify:
  - name: mail
    platform: smtp
    server: !secret smtp_url 
    port: 587
    timeout: 15
    sender: !secret smtp_from
    encryption: starttls
    username: !secret smtp_user
    password: !secret smtp_password
    recipient:
      - !secret smtp_to_home
      - !secret smtp_to_work
    sender_name: My Home Assistant

# ring:
#   username: !secret ring_username
#   password: !secret ring_password

binary_sensor:
  - platform: hikvision
    host: !secret nvr_host
    port: 80
    ssl: false
    username: !secret nvr_username
    password: !secret nvr_password
    customize:
      motion:
        delay: 30
  - platform: template
    sensors:
      # True if there's an update available for supervisor
      updater_supervisor:
        friendly_name: 'Updater - Supervisor'
        device_class: problem
        entity_id:
        - sensor.supervisor_updates
        value_template: "{{ state_attr('sensor.supervisor_updates', 'current_version') != state_attr('sensor.supervisor_updates', 'newest_version') }}"
        availability_template: "{{ (states('sensor.supervisor_updates') | int(-1)) > -1 }}"

      # True if there's updates available for any HACS components
      updater_hacs:
        friendly_name: 'Updater - HACS'
        device_class: problem
        entity_id:
        - sensor.hacs
        value_template: "{{ states('sensor.hacs') | int > 0 }}"

      # True if there's updates available for any addons
      updater_addons:
        friendly_name: 'Updater - Addons'
        device_class: problem
        entity_id:
        - sensor.supervisor_updates
        value_template: "{{ states('sensor.supervisor_updates') | int > 0 }}"

alert:

# Update is available - un-acknowledgeble, auto-dismiss, me only
# Wait 5 minutes before first to give core config check time to run
  ha_update_available:
    name: HA has an update
    entity_id: binary_sensor.updater
    state: 'on'
    can_acknowledge: false
    repeat: 
    - 5
    - 360
    title: 'Update for HA available'
    message: "New version is {{ state_attr('binary_sensor.updater', 'newest_version') }}. Currently on {{ states('sensor.current_version') }}"
    notifiers:
    - 'me'
    data:
      tag: 'ha-update-available'
      url: 'http://hassio.local/hassio/addon/core_check_config'
      ttl: 21600

  # Supervisor update is available - un-acknowledgeable, auto-dismiss, me only
  supervisor_update_available:
    name: Supervisor has an update
    entity_id: binary_sensor.updater_supervisor
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: 'Update for HA Supervisor available'
    message: "New version is {{ state_attr('sensor.supervisor_updates', 'newest_version') }}. Currently on {{ state_attr('sensor.supervisor_updates', 'current_version') }}"
    notifiers:
    - 'me'
    data:
      tag: 'supervisor-update-available'
      url: 'http://hassio.local/hassio/dashboard'
      ttl: 21600

  # HACS repos have updates available - unacknowledgeable, auto-dismiss, me only
  hacs_update_available:
    name: HACS repos have updates
    entity_id: binary_sensor.updater_hacs
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: "Updates available in {{ states('sensor.hacs') }} HACS repo{% if states('sensor.hacs') | int > 1 %}s{% endif %}"
    message: ""
    notifiers:
      - 'me'
    data:
      tag: 'hacs-update-available'
      url: 'http://hassio.local/hacs/installed'
      ttl: 21600

  # Addons have updates available - unacknowledgeable, auto-dismiss, me only
  addon_update_available:
    name: Addons have updates
    entity_id: binary_sensor.updater_addons
    state: 'on'
    can_acknowledge: false
    repeat: 360
    title: "Updates available for {{ states('sensor.supervisor_updates') }} HA addon{% if states('sensor.supervisor_updates') | int > 1 %}s{% endif %}"
    message: ""
    notifiers:
    - 'me'
    data:
      tag: 'addon-update-available'
      url: 'http://hassio.local/hassio/dashboard'
      ttl: 21600

cast:
  media_player:
    - host: !secret nest_hub_host
    - host: !secret google_home_host
    - host: !secret lenovo_clock_host
    - host: !secret chromecast_video_host

camera:
  - platform: mjpeg
    mjpeg_url: !secret cam1_url
    name: cam1
    username: !secret cam1_username
    password: !secret cam1_password
  - platform: mjpeg
    mjpeg_url: !secret cam2_url
    name: cam2
    username: !secret cam2_username
    password: !secret cam2_password
  - platform: generic
    name: nvr_cam1
    username: !secret nvr_username
    password: !secret nvr_cam_password
    authentication: digest
    still_image_url: !secret nvr_cam1_still_url
    stream_source: !secret nvr_cam1_rtsp_url
  - platform: generic
    name: nvr_cam2
    username: !secret nvr_username
    password: !secret nvr_cam_password
    authentication: digest
    still_image_url: !secret nvr_cam2_still_url
    stream_source: !secret nvr_cam2_rtsp_url
  - platform: generic
    name: nvr_cam3
    username: !secret nvr_username
    password: !secret nvr_cam_password
    authentication: digest
    still_image_url: !secret nvr_cam3_still_url
    stream_source: !secret nvr_cam3_rtsp_url
  - platform: generic
    name: nvr_cam4
    username: !secret nvr_username
    password: !secret nvr_cam_password
    authentication: digest
    still_image_url: !secret nvr_cam4_still_url
    stream_source: !secret nvr_cam4_rtsp_url
  # - platform: onvif
  #   host: !secret nvr_host
  #   username: !secret nvr_username
  #   password: !secret nvr_password
  #   name: Annke
  #   profile: 1
  #   port: 8000

# glances:
#   - host: !secret glances_host
#   - port: 61209

google_assistant:
  project_id: !secret google_project_id
#  api_key: !secret google_api_key
  service_account: !include google.conf
  report_state: true
  exposed_domains:
    - switch
    - light

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

grocy:
  url: !secret grocy_api_host
  api_key: !secret grocy_api_key
  verify_ssl: false
  port: 9192
  sensor:
    - enabled: true
  binary_sensor:
    - enabled : true

rest_command:
  assistant_broadcast:
    url: !secret google_assistant_url
    method: POST
    content_type: 'application/json'
    payload: !secret google_assistant_payload_broadcast
    
  assistant_converse:
    url: !secret google_assistant_url
    method: POST
    content_type: 'application/json'
    payload: !secret google_assistant_payload_converse

  assistant_relay:
    url: !secret google_assistant_url
    method: POST
    content_type: 'application/json'
    payload: !secret google_assistant_payload_relay

  grocy_add_task:
    url: !secret grocy_addtask_url
    method: POST
    headers:
      GROCY-API-KEY: !secret grocy_api_key
      accept: 'application/json'
    payload: '{"name":"{{ task_name }}","description":"{{ task_description }}","due_date":"{{ task_due }}","category_id":"","assigned_to_user_id":"1"}'
    content_type:  'application/json'
    verify_ssl: false

timer:
  charge:
    duration: '04:00:00'
  light_up:
    duration: '00:05:00'
  light_down:
    duration: '00:05:00'

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

input_boolean:
  alarm:
    name: Track alarm state
    icon: mdi:alarm-bell

input_select:
  home_mode:
    name: Home Mode
    options:
      - Day
      - Night
      - Away
      - Vacation
      - House Keeping
      - Guest
    initial: Day
    icon: mdi:message-settings-variant

input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 5
    delay_time: 1
    trigger_time: 1
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

speedtestdotnet:
  scan_interval:
    minutes: 720
  monitored_conditions:
    - ping
    - download
    - upload

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# mqtt:
#   broker: a0d7b954-mqtt
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   client_id: home-assistant

minio:
  host: !secret minio_host
  port: 8000
  access_key: !secret minio_access_key
  secret_key: !secret minio_secret_key
  secure: true

folder_watcher:
  - folder: /config/www/sync
    # patterns:
    #   - 'sync*.log'

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  profiles:
    - Julien
    - Mojca
    - Mia 
    - Evy
  # measures:
  #   - weight_kg
  #   - fat_mass_kg

########### CUSTOM COMPONENTS ########### 

hacs:
  token: !secret hacs_token

#breaking_changes:

shelly:

edgeos:
  host: !secret edge_os_host
  ssl: !secret edge_os_ssl
  username: !secret edge_os_username
  password: !secret edge_os_password
#  cert_file: !secret ssl_certificate
  monitored_interfaces:
    - eth0
    - eth1
    - eth2
    - eth3
    - eth4
  monitored_devices:
    - iphone-x
    - iphone-5S
    - lumia
    - oneplus-onex 
  unit: 'M'

device_tracker:
  - platform: edgeos
    hosts:
      - iphone-x
      - iphone-5S
      - lumia
      - oneplus-onex

  - platform: edgeos_cmd
    host: !secret edge_os_host
    username: !secret edge_os_admin_username
    password: !secret edge_os_admin_password
    interval_seconds: 60
    consider_home: 180
    new_device_defaults:
      track_new_devices: false

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: !secret smartmi_ip
    token: !secret smartmi_token

ffmpeg:

image_processing:
  - platform: deepstack_object
    ip_address: 192.168.2.140
    port: 5000
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    targets:
      - person
      - cat
    source:
      - entity_id: camera.nvr_cam1

########### LOVELACE ########### 

# lovelace:
#   mode: yaml
#   resources:
#     - url: /community_plugin/compact-custom-header/compact-custom-header.js
#       type: module
#     - url: /community_plugin/weather-card/weather-card.js
#       type: module
#     - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
#       type: js
#     - url: /community_plugin/mini-graph-card/mini-graph-card.js
#       type: module
#     - url: /community_plugin/button-card/button-card.js
#       type: module
#     - url: /community_plugin/lovelace-card-tools/card-tools.js
#       type: js
#     - url: /community_plugin/lovelace-auto-entities/auto-entities.js
#       type: js
#     - url: /community_plugin/decluttering-card/decluttering-card.js
#       type: module
#     - url: /community_plugin/fitbit-card/fitbit-card.js
#       type: js

########### INCLUDES ########### 

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
sensor: !include sensors.yaml
switch: !include switchs.yaml
group: !include groups.yaml
person: !include persons.yaml
intent_script: !include intent_scripts.yaml