########### DEFAULT CONFIG ########### 
homeassistant:
  packages: !include_dir_named packages/ 
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation
  unit_system: metric
  time_zone: Europe/Brussels
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  allowlist_external_dirs:
    - /config
  external_url: !secret http_ext_url

http:
  # base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.2.0/24
    - 192.168.3.0/24

browser_mod:
config:
conversation:
discovery:
history:
logbook:
sun:
system_health:
updater:
map:
mobile_app:
ssdp:
zeroconf:

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

logger:
  default: warn
  logs:
#    custom_components.hacs: debug
    homeassistant.components.withings: critical
#    custom_components.signalmessenger: info
#    homeassistant.components.netatmo: debug

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 15
  include:
    entities:
      - group.windows
      - group.doors
  exclude:
    domains:
      - updater
      - device_tracker
      - group
      - scene
      - script
    entities:
      - sun.sun

hacs:
  token: !secret hacs_token

########### PLATFORMS ########### 

google_assistant:
  project_id: !secret google_project_id
#  api_key: !secret google_api_key
  service_account: !include google.conf
  report_state: true
  exposed_domains:
    - switch
    - light

# mqtt:
#   broker: a0d7b954-mqtt
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   client_id: home-assistant

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username: homeassistant
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state

########### LOVELACE ########### 

lovelace:
  mode: yaml
  resources:
    # - url: /hacsfiles/compact-custom-header/compact-custom-header.js
    #   type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: js
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/fitbit-card/fitbit-card.js
      type: js
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js
      type: module



