########### DEFAULT CONFIG ########### 
homeassistant:
  name: Home
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation
  unit_system: metric
  time_zone: Europe/Brussels
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  whitelist_external_dirs:
    - /config

http:
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3
  # cors_allowed_origins:
  #   - https://google.com
  #   - https://home-assistant.io
  # use_x_forwarded_for: True
  # trusted_networks:
  #   - !secret trusted_ip
  #   - !secret trusted_ip_2

frontend:
config:
conversation:
discovery:
history:
logbook:
sun:
system_health:
updater:

logger:
  default: warn
  logs:
    homeassistant.components.recorder: debug

recorder:
  purge_interval: 1
  purge_keep_days: 30
  include:
    entities:
      - group.windows
      - group.doors
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
      - group
      - scene
      - script
    entities:
      - sun.sun

########### PLATFORMS ########### 

#light:
#  - platform: hue
#    host: !secret hue_host
#  - platform: xiaomi_miio
#    name: Xiaomi Philips E14
#    host: !secret philips_e14_host
#    token: !secret philips_e14_token
#    model: philips.light.candle

tts:
  - platform: google_translate
    service_name: google_say

hacs:
  token: 882cb4eb31c71429b43e5b60d472a6fe7961fcad

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

# curl -X GET https://api.telegram.org/botYOUR_API_TOKEN/getUpdates
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_id_ju
      - !secret telegram_chat_id_mo

notify:
  - name: ju
    platform: telegram
    chat_id: !secret telegram_chat_id_ju
  - name: mo
    platform: telegram
    chat_id: !secret telegram_chat_id_mo
  - name: Google Assistant
    platform: rest
    resource: !secret google_msg_url

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring

cast:
  media_player:
    - host: !secret google_home_host
    - host: !secret chromecast_video_host

camera:
  - platform: mjpeg
    mjpeg_url: !secret cam1_url
    name: cam1
    username: !secret cam1_username
    password: !secret cam1_password
  - platform: mjpeg
    mjpeg_url: !secret cam2_url
    name: cam2
    username: !secret cam2_username
    password: !secret cam2_password

google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - switch
    - light

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

timer:
  charge:
    duration: '04:00:00'

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

input_boolean:
  alarm:
    name: Track alarm state
    icon: mdi:mdi-alarm-light

input_select:
  home_mode:
    name: Home Mode
    options:
      - Day
      - Night
      - Away
      - Vacation
      - House Keeping
      - Guest
    initial: Day
    icon: mdi:message-settings-variant

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 5
    delay_time: 1
    trigger_time: 1
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

speedtestdotnet:
  scan_interval:
    minutes: 720
  monitored_conditions:
    - ping
    - download
    - upload

########### INCLUDES ########### 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switchs.yaml
