- platform: template
  covers:
    mezzanine:
      friendly_name: "Mezzanine Shade"
      open_cover:
        service: script.mezzanine_shade_up
      close_cover:
        service: script.mezzanine_shade_down
      stop_cover:
        service: script.mezzanine_shade_stop
