- platform: broadlink
  # host: !secret broadlink_rm_host
  mac: !secret broadlink_rm_mac
  # timeout: 15
  switches:
# Home Cinema Light
    prise1:
      friendly_name: "prise1"
      command_on: 'sgDUAQofCh4KHgofCh4KHgofCR8KHgofCh4KHgofHgoKHx0LCh4eCwoeHgsJHwoeCh4fCgoAATgKHwkfCh4KHgofCh4KHgofCh4KHwkfCh4KHh8KCh4eCwkfHgoKHx4KCh8JHwoeHgsKAAE4Ch4KHwkfCh4KHwkfCh4KHwoeCh4KHwkfCh4eCwoeHgsJHx4KCh8dCwofCR8KHh4KCgABOQoeCh4KHwoeCh8JHwoeCh4KHwkfCh8JHwkfHgsJHx4KCh8eCgoeHwoJHwofCR8eCgoAATkKHgoeCh8KHgoeCh8JHwofCR8KHgoeCh8JHx4LCR8eCgofHQsKHh4LCR8KHgofHgoKAAE5CR8KHgoeCh8KHgofCR8KHgofCR8KHgofCR8eCgofHgoKHx4KCh4eCwoeCh4KHx4KCgABOQkfCh4KHwkfCh8JHwkfCh8JHwkfCh4KHwkfHgoKHx4KCh8eCgoeHgseCh4LHgoeCgoAATkKHgoeCh8KHgoeCh8KHgoeCh8KHgoeHgsJHx4KCh8eCgofHgoKHh4LHgoeCx4KHgoKAAE5Ch4KHwkfCh4KHwkfCh4KHwkfCh4KHh8KCh4fCgoeHgsJHx4KCh8eCh4LHgoeCh4LCgAF3AoeHgs='
      command_off: 'sgBwAgoeCh8JHwofCR8JHwofCR8JHwofCR8JHwkgHQsJHx4LCR8eCwkfHQsKHh4LCR8KHwkAATkJHwofCR8KHwkfCR8JHwofCR8JHwoeCh8JHx4LCR8eCwkfHgoKHx0LCR8eCwkfCh8JAAE5CR8KHgofCR8KHgofCR8KHwkfCR8KHwkfCR8eCwkfHgsJHx0LCh8dCwkfHgsJHwoeCgABOQoeCh8JHwoeCh4KHwkfCh8JHwoeCh8JHwoeHgsJHx4KCh8eCgofHQsKHx0LCR8KHwkAATkJHwofCR8JIAkfCR8KHgofCR8KHgofCR8KHx0LCh4eCwkfHgoKHx4KCh8dCwoeCh8JAAE5CSAJHwkfCh8JHwkfCh8JHwkfCh8JHwkfCh8dCwkfHgsJHx4LCR8eCgofHgoKHwkfCQABOgkfCR8JHwofCR8JHwofCR8KHgofCR8JIAkfHQsKHx0LCR8eCwkfHgsJHx4KCh8JHwoAATkJHwkfCh4KHwoeCh4KHwoeCh8JHwoeCh8JHx4LCR8dCwofHQsKHh4LCR8eCwkfCR8KAAE5CR8KHgofCR8KHgofCR8KHgofCR8KHh4LCR8eCwkfHgsJHx4KCh8dCx4LHQseCx0LCQABOgkfCR8JHwofCR8JHwofCR8KHgofCR8eCwkfHQsKHx0LCR8eCwkfHgoeCx4KHgseCgoAATkJHwofCR8JHwofCR8JHwoeCh8JHwoeHgsKHh4LCR8eCwkfHgoKHx0LHgsdCx4KHgsJAAE5Ch4KHwkfCh8JHwkfCh4KHwkfCh4KHx4KCh8dCwofHQsJHx4LCR8eCh4LHgsdCx4KCgAF3AkfHgsJHx4K'
# Sport Room
    prise2:
      friendly_name: "prise2"
      command_on: 'sgB6AB0LCR8eCx0LHgsdCx4LCQABOQkfCh8JHwkfCh8JHwkfCh8JHwkfCh8dCwofHQsJHx4LCR8dCwofHQseCx0LHgsdCwkAATkKHwkfCR8KHwkfCh4KHwkfCR8KHwkfHgsJHx0LCh8dCwkfHgsJHx4LHQseCh4LHQsKAAXcAAAAAAAAAAAAAAAAAAA='
      command_off: 'sgBWAh0LCh4eCwkfHgsJHx4KCh8JHwoAATgKHwkfCh4KHwkfCh8JHwkfCh4KHwkfHgsJHwkfCh8dCwkfHgsJHx4LCR8dCwofCR8KAAE4Ch8JHwkfCh8JHwoeCh8JHwoeCh8JHx4KCh8JHwkfHgsJHx4LCR8eCgofHQsKHwkfCQABOQoeCh8JHwoeCh8KHgofCR8JHwofCR8eCgofCR8KHh4LCR8eCwkfHgsJHx0LCh8JHwkAAToJHgofCR8KHwkfCSAJHwkfCR8KHwkfHgsJHwkfCh4eCwkfHgsJHx4KCh8eCgofCR8JAAE5Ch8JHwoeCh8JHwoeCh8JHwofCR8JHx4LCR8KHgofHQsKHh4LCR8eCwkfHgsJHwkfCgABOQkfCR8KHgofCh4KHgofCSAJHwkfCR8eCwkfCh4KHx0LCh4eCwkfHgsJHx4LCR8JHwoAATkJHwkfCh8JHwoeCh8JHwoeCh8JHwoeHgsKHgofCR8eCgofHQsKHh4LCR8eCwkfCh8JAAE5Ch4KHgofCR8KHgofCh4KHwkfCR8KHx0LCh4KDQQEBAsJHx4KCh8eCgofHgoeCx4KHgsdCwkAATkKHwkfCSAJHwkfCh4KHwkfCh4KHwkfHgoKHx4KCh8dCwkfHgsJHx4LHQseCh4LHgsJAAE5CR8KHgofCR8KHgofCR8KHwkfCR8KHh4LCh4eCwkfHgoKHx4KCh8dCx4LHQseCh4LCQABOQofCR8JHwoeCh8JHwofCR8KHwkeCh8eCgofHQsKHh4LCR8eCwkfHgoeCx4KHgseCgoABdwJIA=='
# Led Up
    prise3:
      friendly_name: "prise3"
      command_on: 'sgDsAQofCSAJHx4LCR8eCwkfCh8JIB0LCgABOgkfCh4KHwkfCh8KHwkfCR8KHwkfCh8eCwkfHgsJHwofCSAdCwkfHwoKHwkfCh8eCgoAAToJHwofCSAJHwofCR8KHwkfCSAJHwkgHQsKHx4KCh8JHwofHgsJHx4LCR8KHwkfHgsJAAE7CR8JHwofCSAJHwkgCR8KHwkfCSAJHx4LCR8eCwkfCh8JHx4LCh8dCwofCR8KHx0LCgABOgofCR8JIAkfCSAJHwofCR8JIAkfCSAdCwofHgoKHwkgCR8eCwkfHgsJHwofCSAdCwkAATsJHwofCR8KHwkfCSAJHwoeCh8JIAkfHgsJHx4LCh8JHwkfHgsKHx0LCh8JHwofHgsJAAE6Ch8JHwkgCR8KHwkfCSAJHwofCR8KHx4LCR8eCwkfCh8JHx4LCR8eCwkfCh8JIB0LCQABOwkfCh8JHwofCR8KHwkfCh8JHwofCR8eCwoeHgsJIAkfCh8eCgofHgoeCx4LHQseCwkAAToKHwkgCR8JIAkfCR8KHwoeCh8JIAkfHgsJHx4LCR8KHwkfHgsJHx4LHgsdCx4LHgsJAAE6Ch8JHwofCSAJHwkfCSAJHwofCR8JIB0LCh8eCgofHgsJHx4LCR8eCx4LHQseCx4LCQAF3AofCR8KHwkfCSAJHw=='
      command_off: 'sgDoAQofHQsKHx4LCR8eCwkfCSAJAAE6Ch4KHwofCR8JIAkfCh8JHwofCR8KHx4KCh8eCgofCR8KHx4LCR8eCwkfHgsJIAkfCQABOgofCh8JHwkgCR8JIAkfCR8KHwkfCh8eCwkfHgsJHwofCSAdCwofHQsJIB0LCh8JHwoAAToJHwofCR8KHwkfCh8JHwofCR8KHwkgHQsJIB0LCh8JIAkfHQsKHx4LCR8eCwkgCR8JAAE6Ch8JHwofCR8KHwkfCh8JHwofCR8KHx4KCh8eCgofCSAJHx4LCR8eCwoeHgsJIAkfCgABOgkfCh8JHwofCR8KHwkfCh8JHwofCR8eCwkfHgsJHwofCSAdCwofHgoKHx4LCR8JIAkAAToKHwkfCh8JHwofCR8KHwkfCh8JHwofHgoKHx4LCR8eCwkfHgsJHx4LHgsdCx4LHgsJAAE6CSAJHwkgCR8JHwofCR8KHwofCR8JHx4LCh4eCwofHgoKHx4KCh8eCx0LHgseCh4LCgABOgkfCh8JHwofCR8KHwkfCR8KHwofCR8eCwkfHgsJHx4LCR8eCwofHQseCx4LHQseCwkAAToKHwkfCh8JIAkfCR8KHwkfCh8JHwofHgoKHx4LCR8eCwkfHgsJHx4LHgsdCx4LHgsJAAXc'
# Lights Outside
    prise4:
      friendly_name: "prise4"
      command_on: 'sgBCAQoeCh8eCgsAATkKHwoeCh8KHgofCh4KHwoeCh8KHgofHgoKHx4LCh4fCgoeCh8KHx4KCh8JHwofHgoKAAE6Ch8KHgofCR8KHwoeCh8KHwkfCh8JHx4KCx4eCwkfHwoKHgofCh8eCgoeCx4KHx4LCQABOgoeCh8KHwoeCh8JHwofCR8KHwoeCh8eCgofHgoLHh4LCh4KHwofHQsKHwoeCh4fCgoAAToKHgofCh4KHwoeCx4KHwoeCh8KHgofHgoLHh4LCR8eCwoeHwoKHh8KHgseCh4LHgsKAAE5Ch8KHgofCh4KHwkfCh4KHwoeCh8KHx4KCh8eCgofHgoLHh4LCh4eCx4KHwoeCx4KCgABOgoeCh8KHgofCh4KHgofCh8KHgofCR8eCwoeHgsKHh8KCh8eCgofHgoeCx4LHgoeCwoABdwAAAAAAAA='
      command_off: 'sgAwAgofCR8KHwkfCh4fCgofHgoKHx4KCh8KHgofHgsJHx4LCh4KHwoAATkKHwkfCh8JHwofCR8KHgofCh8JHwofHgoKHx4KCh8eCgofCh4KHx4KCh8eCwoeCh8KAAE5Ch8KHgofCh4KHwkfCh8KHgofCR8KHx4KCh8eCwkfHgoLHgofCR8eCwoeHgsKHgofCgABOQofCh4KHwoeCh8KHgofCh4KHwoeCh8eCwkfHgsJHx4LCh4KHwoeHwoKHh8KCh8KHgoAATkKHwoeCh8KHwkfCh8JHwofCh4KHwoeHgsKHh4LCh4fCgofCR8KHx4KCh8eCgofCh4KAAE6Ch4KHwoeCh8JHwofCh4KHwoeCh8KHh8KCh4fCgofHgoKHwoeCh8eCgseHgoKHwofCQABOgofCR8KHwkfCh4LHgofCh4KHwkfCh8eCgofHgoKHx4LCR8KHwoeHgsKHh4LCh4KHwoAATkKHwoeCx4KHwkfCh4KHwoeCh8KHgofHgoLHh4LCh4eCwoeCh8KHx4KCh8eCgofCh4KAAE6Ch4KHwoeCh8KHgoeCx4KHwoeCh8JHx4LCh4fCgofHgoKHx4KCh8eCh8KHgseCh4LCgABOQofCh4KHwoeCh8KHgofCh4KHwoeCh8eCgofHgsJHx4LCR8eCwkfHwoeCx4KHgseCgoAAToKHgofCh4KHwoeCh8KHgofCh4KHwoeHgsKHh8KCh4eCwofHgoKHx4KHwoeCx4KHwoKAAXcCh4eCwoeHwo='
    sharp:
      friendly_name: "Sharp"
      command_on: 'JgDMAAw5CxcLGAsXCzoLGAs7CxcLOgsYChkKOwoYCjsLGAsABc4NOQwWCxgLFws6DDkMFws7CxYMOgs6DBcKOwwWDDkMAAWIDTkMFwoYCxgKOwwWCzoNFgs6DBcLFws6DBcLOgwWCwAFzww6CxgLFgsYCzsLOgsXCzoMFws6DDkMFgw5DBcLOwsABYkMOQwWDBcLFww5DBcLOgwXCzoLGAoZCjsKGAo7DBcKAAXPCzsKGAsYCxcLOgs6CxgLOgsXCzsLOgoZCjsLFws6CwANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgDMAAw5DBYLGAsYCzoLOwo7CxcKOwsYChgKOwsYCjsMFgsABawMOgwWChkKGQk7DBcKGAo7DBcLOgw5DBcLOgsXCzsLAAWrDDoLGAoYCxcLOws7CjoMFws7CxYLGAs6DBYLOwsXCwAFrAw5DBcLFwsYCzoMFgsYCzoMFgs7CzoLGAo7DBcLOgsABasNOQwWCxgLGAs6CzoLOgsXCzsLGAoYCjsLGAo7DBYKAAWtDDoLFwoZChgKOwsYChgKOwwXCzoMOQwXCzoLFws7CwANBQAAAAAAAAAAAAAAAA=='
    bose_volume:
      friendly_name: "Bose Volume"
      command_on: 'JgCQAAABJZQSExE4ERQROBI4EjcSExE4EhMRFBEUERMSExE4EhMRORI3ETkRExITERQRExITERQRFBETEjgROBI4ETgSOBE4EQAFQAABJpMSExE4EhMRORE4ETkRExI4EhMRExITERQRExI4ERQROBE5EjcRFBETEhMRFBEUERMSExEUETgSOBE4ETkROBE5EQANBQAAAAAAAAAA'
      command_off: 'JgCQAAABJpMRExI4ERMSOBE4EzcRFBE4ERQRExITERQRFBE4ERQROBITETgSExEUERQRExITERQROBEUETgSOBI3EzcROBI4EQAFQAABJZQSExE4ERQROBI4ETgSExE4EhMRFBEUERMSExE4ExIRORETEjgRFBETEhMRFBETExIRORETEjgROBI4ETgRORE4EQANBQAAAAAAAAAA'
    bose_system:
      friendly_name: "Bose System"
      command_on: 'JgCQAAABJpMSExI4EhIRORI3EjgRExI4ERQRExITEhMSEhM3ERQROBEUERQROBE4EhMRFBE4EhMSOBE4EhMRExI4ETgSExE5EQAFQAABJZQSEhI4EhMROBE5ETgRFBE4EhMRFBETEhMRFBE4EhMROBITERQROBI4ERQRExE5ERMSOBE4EhMRFBE4EjgRFBE4EQANBQAAAAAAAAAA'
      command_off: 'JgCQAAABJpMSExI4EhIRORI3EjgRExI4ERQRExITEhMSEhM3ERQROBEUERQROBE4EhMRFBE4EhMSOBE4EhMRExI4ETgSExE5EQAFQAABJZQSEhI4EhMROBE5ETgRFBE4EhMRFBETEhMRFBE4EhMROBITERQROBI4ERQRExE5ERMSOBE4EhMRFBE4EjgRFBE4EQANBQAAAAAAAAAA'
# Store
    # store_mezzanine:
    #   friendly_name: "Store Mezzanine"
    #   command_on: 'sgDMAQkTChMKEwkTChMVCAoTChIKEwoTCRMKEwoTChILEwkTFQgKEgsSChMUCRQIFQgKEwoTChIKEwoTFAkUCBSjpBMUCAsSFQgKEwoTChIUCRQJChIKExUIFAkUCBUIFAkKEgoTFQgUCRQIFQgVCBQJChIVCAoTFAgKEwoTChMUCBUIChMKEwkTChMKEgsSChMVCAoTChIKEwoTChIKEwoTChMKEgoTFAkKEwoSChMVCBQJFAgKEwoTChIKEwoTFAkUCBWipBMVCAoTFAgKEwoTChIVCBUIChMKEhUIFAkUCBUIFQgKEwoSFQgUCRQJFAgVCBQJChIVCAoTFAgLEgoTChMUCBUIChMKEwoTCRMKEwoTCRMVCAoTChMJEwoTChMJFAoSChMKEwoSFQgKEwoSCxIVCBQJFAgKEwoTChILEgoTFQgUCBWipBMVCAoTFAgKEwoTCRMVCBQJChMKEhUIFQgUCBUIFQgKEwoSFQgVCBQJFAgVCBQJChMUCAoTFAgLEgoTChMUCRQIChMKEwoSChMKEwoTChIVCAoTChILEgoTChMKEwkTChMKEwoSFQgKEwoTChIVCBQJFAkJEwoTChILEgoTFQgUCBUABdwJEwoTChMKEgsTCRM='
    #   command_off: 'sgDKAQkUCRMJFAkUFAgKEwkUCRQJEwoTChMJEwoTChMJFAkUCRMUCQkUFAgUCQoTFAgVCAoTFAkJFBMJFAgVo6MTFQgKExQIChQJEwkUFAkUCAoTChMUCRMJFQgUCRQIChMKExQJFAkTCRQJFAgUCQoTFAkJExUIChMJFAkTFQgUCQkUCRMKEwkUCRQJEwoTFAgKEwoTCRQJEwoUCRMKEwkTChMKEwoTCRQTCQoTFAkUCAoTFAkUCAoTFAkKExQIFQgUo6MUFAgKExQJCRQJFAkTFAkUCQkTChMUCRQJFAgUCRQJCRQJExQJFAkUCRMJFAkUCQkTFAkJFBQIChMKEwkUEwkUCQoTCRMKEwoTChMJEwoTFAkJFAkTChMKEwkUCRMKEwoTCRQJEwoTChMUCAoTFAkUCAoTFAkUCQkTFQgKExQJFAgUo6MUFAkJFBMJChMJFAkTFAkUCQkTChMUCRQJFAgVCBQJCRQJExUIFAkUCRQIFAkUCQkTFAkKExQJCRMKEwoTFAkTCgkTCRQJFAkTChMJFAkUEwkKEwkUCRQJEwoTCRQJEwoTChMJEwoTCRQUCAoTFAkUCQkUEwkUCQkUFAgKExQJFAgUAAXcCRMKEwoTCRMKEwoTCRQ='
      


# - platform: broadlink
  # host: !secret broadlink_mp1_host
  # mac: !secret broadlink_mp1_mac
  # type: mp1
  # friendly_name: 'powerstrip2'
  # slots:
  #     slot_1: 'powerstrip2 PLUG1'
  #     slot_2: 'powerstrip2 PLUG2'
  #     slot_3: 'powerstrip2 PLUG3'
  #     slot_4: 'powerstrip2 PLUG4'

- platform: template
  switches:
    belgacom:
      value_template: "{{ is_state('switch.tv', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.watch_tv
      turn_off:
        service: script.turn_on
        entity_id: script.stop_watching
    ps3:
      value_template: "{{ is_state('switch.ps3', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.watch_ps3
      turn_off:
        service: script.turn_on
        entity_id: script.stop_watching
    apple:
      value_template: "{{ is_state('switch.apple', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.watch_movies
      turn_off:
        service: script.turn_on
        entity_id: script.stop_watching
    chromecast_audio:
      value_template: "{{ is_state('switch.chromecastaudio', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.listen_audio
      turn_off:
        service: script.turn_on
        entity_id: script.stop_watching
    chromecast_video:
      value_template: "{{ is_state('switch.chromecastvideo', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.watch_video
      turn_off:
        service: script.turn_on
        entity_id: script.stop_watching
    table:
      friendly_name: "table"
      value_template: "{{ is_state('switch.table', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.table_up
      turn_off:
        service: script.turn_on
        entity_id: script.do_nothing
    store:
      value_template: "{{ is_state('switch.store', 'on') }}"
      turn_on:
        - service: script.turn_on
          entity_id: script.living_left_shade_down
        - service: script.turn_on
          entity_id: script.living_right_shade_down
        - service: script.turn_on
          entity_id: script.mezzanine_shade_down
      turn_off:
        - service: script.turn_on
          entity_id: script.living_left_shade_up
        - service: script.turn_on
          entity_id: script.living_right_shade_up
        - service: script.turn_on
          entity_id: script.mezzanine_shade_up 
    alarm_arm_away:
      value_template: "{{ is_state('input_boolean.alarm', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.alarm
        - service: alarm_control_panel.alarm_arm_away
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_code
        - service: script.alarm_on_loud
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.alarm
        - service: alarm_control_panel.alarm_disarm
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_code
        - service: script.alarm_off_loud
    alarm_arm_home:
      value_template: "{{ is_state('input_boolean.alarm', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.alarm
        - service: alarm_control_panel.alarm_arm_home
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_code
        - service: script.alarm_on_silent
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.alarm
        - service: alarm_control_panel.alarm_disarm
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_code
        - service: script.alarm_off_silent
    chargeur:
      friendly_name: "chargeur"
      value_template: "{{ is_state('timer.charge', 'active') }}"
      turn_on:
        - service: timer.start
          entity_id: timer.charge
        - service: homeassistant.turn_on
          entity_id: switch.prise3
      turn_off:
        - service: timer.cancel
          entity_id: timer.charge
        - service: homeassistant.turn_off
          entity_id: switch.prise3
    # glances_addon:
    #   value_template: "{{ is_state('sensor.glances_addon', 'started') }}"
    #   turn_on:
    #     service: hassio.addon_start
    #     data:
    #       addon: a0d7b954_glances
    #   turn_off:
    #     service: hassio.addon_stop
    #     data:
    #       addon: a0d7b954_glances
    adb_addon:
      value_template: "{{ is_state('sensor.adb_addon', 'started') }}"
      turn_on:
        service: hassio.addon_start
        data:
          addon: a0d7b954_adb
      turn_off:
        service: hassio.addon_stop
        data:
          addon: a0d7b954_adb
    mariadb_addon:
      value_template: "{{ is_state('sensor.mariadb_addon', 'started') }}"
      turn_on:
        service: hassio.addon_start
        data:
          addon: core_mariadb
      turn_off:
        service: hassio.addon_stop
        data:
          addon: core_mariadb

# PS3
# - platform: wake_on_lan
#   name: "PS3 WOL"
#   mac_address: !secret ps3_mac

- platform: command_line
  switches:
    send_text_to_nest_hub:
      command_on: "catt cast_site 'https://dummyimage.com/1080x728/fff/0011ff.png&text=Message+de+Home+Assistant'"
      command_off: "catt stop"
      friendly_name: Cast Text
