title: Home Assistant 

button_card_templates:
#02A9F4
  header:
    color_type: label-card
    color: rgb(2, 169, 244)
    styles:
      card:
        - padding: 5px 15px

  header_group:
    color_type: label-card
    color: rgb(44, 109, 255)

  window:
    icon: mdi:window-closed
    styles:
      icon:
        - transform: rotate(270deg)
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:window-open  
        styles:
          icon:
            - animation: blink 2s ease infinite 
            - transform: rotate(270deg)

  velux:
    icon: mdi:window-closed
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:window-open  
        styles:
          icon:
            - animation: blink 2s ease infinite 

  door:
    icon: mdi:door-closed
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:door-open  
        styles:
          icon:
            - animation: blink 2s ease infinite 

  motion:
    icon: mdi:run
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        styles:
          icon:
            - animation: blink 2s ease infinite 

  smoke:
    icon: mdi:fire
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        styles:
          icon:
            - animation: blink 2s ease infinite 

  light:
    icon: mdi:lightbulb-outline
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    state:
      - value: "on"
        color: yellow 
        icon: mdi:lightbulb-on-outline

  plug:
    icon: mdi:power-plug
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    state:
      - value: "on"
        color: yellow 

  person:
    hold_action:
      action: more-info
    state:
      - value: "home"
        color: green 

  battery:
    icon: mdi:battery
    color_type: icon
    show_state: true
    state:
    - value: 10
      operator: '<'
      color: "#FF0000" #red
      icon: "mdi:battery-10"
    - value: 20
      operator: '<='
      color: "#ff6600" #red orange
      icon: "mdi:battery-20"
    - value: 30
      operator: '<='
      color: "#ff9933" #dark orange
      icon: "mdi:battery-30"
    - value: 40
      operator: '<='
      color: "#ffcc00" #light orange
      icon: "mdi:battery-40"
    - value: 50
      operator: '<='
      color: "#FFFF00" #yellow
      icon: "mdi:battery-50"
    - value: 60
      operator: '<='
      color: "#FFFF00" #yellow
      icon: "mdi:battery-60"
    - value: 70
      operator: '<='
      color: "#FFFF00" #yellow
      icon: "mdi:battery-70"
    - value: 80
      operator: '<='
      color: "#CCFF33" #yellow green
      icon: "mdi:battery-80"
    - value: 90
      operator: '<='
      color: "#66FF33" #light green
      icon: "mdi:battery-90"
    - value: 100
      operator: '<='
      color: "#279b37" #dark green
      icon: "mdi:battery"


resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module

views:
  - !include ui-lovelace/010_home.yaml
  - !include ui-lovelace/020_security.yaml
  - !include ui-lovelace/030_weather.yaml
  - !include ui-lovelace/040_system.yaml
  - !include ui-lovelace/050_people.yaml  
  - !include ui-lovelace/060_finance.yaml  