title: Home Assistant 

button_card_templates:
  header:
    styles:
      card:
        - padding: 5px 15px
        - background-color: var(--paper-item-icon-active-color)
      name:
        - text-transform: uppercase
        - color: var(--primary-background-color)
        - justify-self: start
        - font-weight: bold
      label:
        - text-transform: uppercase
        - color: var(--primary-background-color)
        - justify-self: start
        - font-weight: bold

  header_red:
    template: header
    styles:
      card:
        - background-color: '#FF0000'

  window_sensor:
    icon: mdi:window-closed
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:window-open  
        styles:
          card:
            - animation: blink 2s ease infinite 

resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module

views:
  - !include ui-lovelace/010_home.yaml
  - !include ui-lovelace/020_security.yaml
  - !include ui-lovelace/030_weather.yaml
  - !include ui-lovelace/040_system.yaml