title: Home Assistant
resources:
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: js
    url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card.js
  - type: module
    url: /community_plugin/monster-card/monster-card.js
views:
  - !include ui-lovelace/010_home.yaml
  - !include ui-lovelace/020_security.yaml
  - !include ui-lovelace/030_weather.yaml
  - !include ui-lovelace/040_weather.yaml