title: Home Assistant 

button_card_templates:

  header:
    color_type: label-card
    color: rgb(44, 109, 214)

  window:
    icon: mdi:window-closed
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:window-open  
        styles:
          icon:
            - animation: blink 2s ease infinite 
    # styles:
    #   icon:
    #     transform: rotate(270deg)

  door:
    icon: mdi:door-closed
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        icon: mdi:door-open  
        styles:
          card:
            - animation: blink 2s ease infinite 

  motion:
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        styles:
          card:
            - animation: blink 2s ease infinite 

  smoke:
    tap_action:
      action: more-info
    state:
      - value: "on"
        color: orange 
        styles:
          card:
            - animation: blink 2s ease infinite 

  light:
    icon: mdi:lightbulb-outline
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    state:
      - value: "on"
        color: yellow 
        icon: mdi:lightbulb-on-outline

  plug:
    icon: mdi:power-plug
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    state:
      - value: "on"
        color: yellow 

resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module

views:
  - !include ui-lovelace/010_home.yaml
  - !include ui-lovelace/020_security.yaml
  - !include ui-lovelace/030_weather.yaml
  - !include ui-lovelace/040_system.yaml