# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/cameras.html

cameras:
  - entity: camera.cam1
  - entity: camera.cam2
  - entity: camera.nvr_cam1
  - entity: camera.nvr_cam2
  - entity: camera.nvr_cam3
  - entity: camera.nvr_cam4
  - entity: camera.nvr_cam1_doods
  - entity: camera.nvr_cam2_doods
  - entity: camera.nvr_cam3_doods
  - entity: camera.nvr_cam4_doods
  - entity: camera.nvr_cam1_local
  - entity: camera.nvr_cam2_local
  - entity: camera.nvr_cam3_local
  - entity: camera.nvr_cam4_local