# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:

    - name: Home
      icon: mdi:home
      path: 'dwains-theme/addons/more_page/home/page.yaml'

    - name: Security
      icon: mdi:home-lock
      path: 'dwains-theme/addons/more_page/security/page.yaml'

    - name: Weather
      icon: mdi:temperature-celsius
      path: 'dwains-theme/addons/more_page/weather/page.yaml'

    - name: Person
      icon: mdi:face
      path: 'dwains-theme/addons/more_page/person/page.yaml'

    - name: Finance
      icon: mdi:calculator
      path: 'dwains-theme/addons/more_page/finance/page.yaml'

    - name: System
      icon: mdi:lan
      path: 'dwains-theme/addons/more_page/system/page.yaml'

    - name: Web Links
      icon: mdi:web
      path: 'dwains-theme/addons/more_page/weblinks/page_secret.yaml'

    - name: Ha View
      icon: mdi:home-assistant
      path: 'dwains-theme/addons/more_page/ha_view/page.yaml'
      data:
        some_data: 'This is some data parsed.'
        some_other_data: 'and some other data.'
