# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:

  - name: Vestibule
    icon: fas:key
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    motion: binary_sensor.motion_sensor_158d00042026f7
    light: switch.shelly_shsw_1_c499ba
    # window:
    door: binary_sensor.door_window_sensor_158d0002c9c949
    # media_player:
    # plant: 
    page_entities:
      entities:
        - entity: sensor.porte_de_devant_last_ding
        - entity: sensor.porte_de_devant_last_motion
        - entity: sensor.porte_de_devant_wifi_signal_category
        - entity: sensor.porte_de_devant_battery
        - entity: sensor.entree_wifi_signal_category

  - name: Garage
    icon: fas:garage
    temperature: sensor.garage_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    motion: binary_sensor.garage_sensor_motion
    light: light.garage_light
    # window:
    # door: 
    # media_player:
    # plant: 
    page_entities:
      entities:
        - entity: sensor.garage_sensor_motion_battery
        - entity: camera.nvr_cam1  
        - entity: image_processing.deepstack_object_cam1
        # - entity: petkit

  - name: Salon
    icon: fas:couch
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion:
    light: group.living_lights
    # window:
    # door: 
    media_player: group.living_medias
    # plant: 
    page_entities:
      entities:
        - entity: binary_sensor.smoke_sensor_158d0001e581ee
        - entity: group.powerstrip1_p402a
        - entity: group.powerstrip2_mp1
        - entity: switch.prise3
        - entity: camera.cam2

  - name: Veranda
    icon: fas:window-restore
    # temperature: 
    # humidity: 
    # motion: 
    # light: 
    # window:
    # door: 
    # media_player:
    # plant: 
    # page_entities:
    #   entities:
    #     - entity: 

  - name: Jardin
    icon: fas:leaf
    temperature: sensor.netatmo_living_room_outside_temperature
    humidity: sensor.netatmo_living_room_outside_humidity
    # motion: 
    # light: 
    # window:
    # door: 
    # media_player:
    # plant: 
    page_entities:
      entities:
        - entity: switch.prise4

  - name: Mezzanine
    icon: fas:store
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    motion: binary_sensor.motion_sensor_158d000276d4da
    light: switch.shelly_shsw_1_c495de
    window: binary_sensor.door_window_sensor_158d000237d1b8
    # door: 
    media_player: media_player.mezzanine
    # plant: 
    page_entities:
      entities:
        - entity: binary_sensor.smoke_sensor_158d0001bbe483

  - name: Chambre Parent
    icon: fas:bed
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion: 
    light: group.spots
    window: binary_sensor.door_window_sensor_158d000232b0ad
    # door: 
    # media_player: alexa
    # plant: 
    page_entities:
      entities:
        - entity: light.gateway_light_7811dcb8f98a
        - entity: binary_sensor.wall_switch_both_158d000237bae7
        - entity: binary_sensor.wall_switch_right_158d000237bae7
        - entity: binary_sensor.wall_switch_left_158d000237bae7
        - entity: fan.xiaomi_smart_fan


  - name: Chambre Mia
    icon: fas:bed
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion: 
    # light: e14 xiaomi
    window: group.windows_mia
    # door: 
    # media_player:
    # plant: 
    page_entities:
      entities:
        - entity: binary_sensor.smoke_sensor_158d00024e8f68 

  - name: Chambre Evy
    icon: fas:bed
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion: 
    light: light.evy_light
    window: group.windows_evy
    # door: 
    media_player: media_player.chambre_evy
    # plant: 
    page_entities:
      entities:
        - entity: binary_sensor.smoke_sensor_158d00028f4032

  - name: Chambre Amis
    icon: fas:user-friends
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion: 
    # light: 
    window: binary_sensor.door_window_sensor_158d000238628c
    # door: 
    # media_player: firetv
    # plant: 
    page_entities:
      entities:
        - entity: switch.prise2

  - name: Salle de Bain
    icon: fas:bath
    temperature: sensor.netatmo_living_room_inside_temperature
    humidity: sensor.netatmo_living_room_inside_humidity
    # motion: 
    # light: 
    window: binary_sensor.door_window_sensor_158d000243645e
    # door: 
    # media_player:
    # plant: 
    # page_entities:
    #   entities:
    #     - entity: 


# rooms:
#   - name: Hallway
#     icon: fas:key
#     light: light.hallway
#     temperature: sensor.hallway_temperature
#     climate: climate.hallway_climate
#     humidity: sensor.halway_humidity
#     motion: binary_sensor.hallway_sensor_motion
#     door: binary_sensor.hallway_door_contact
#     window: binary_sensor.hallway_window_contact
#     vacuum: 
#       entity: vacuum.rockrobo
#       camera: camera.rockrobo_map
#     plant: plant.hallway_plant
#     media_player: media_player.awesome_hallway_tv
#     more_entities:
#       entities:
#         - entity: sensor.hallway_motion_battery_level
#         - entity: sensor.smokedetector_battery
#   - name: Garage
#     icon: fas:garage
#     light: group.garage_lights
#     door: group.garage_doors
#     addons:
#       - name: Hello room
#         icon: fas:puzzle-piece
#         path: 'dwains-theme/addons/rooms/hello-room/page.yaml'
#         button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
#         data:
#           some_data: 'This is some data parsed.'
#           some_other_data: 'and some other data.'
#           entity: vacuum.roborock
#   - name: Bedroom
#     icon: fal:bed
#     more_entities:
#       columns: 2 #optional
#       entities:
#         - entity: sensor.name1
#         - entity: sensor.name2
#     page_entities:
#       columns: 1 #optional
#       entities:
#         - entity: sensor.name1
#         - entity: sensor.name2