timer:
  charge:
    duration: '04:00:00'

automation:
  # Turn on prise3
  - id: CH001
    alias: Turn on prise3
    trigger:
      platform: time
      at: "02:00:00"
    action:
    - service: timer.start
      entity_id: timer.charge
    - service: homeassistant.turn_on
      entity_id: switch.prise3
    - service: homeassistant.turn_on
      entity_id: switch.prise3
  # Turn off prise3 at the end of timer
  - id: CH002
    alias: Turn off prise3 when end timer
    trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.charge
    action:
    - service: homeassistant.turn_off
      entity_id: switch.prise3
  # Turn off mp1 for bedtime
  - id: CH003
    alias: Turn off mp1 after we go to bed
    trigger:
      platform: time
      at: '23:59:00'
    action:
    - service: homeassistant.turn_off
      entity_id: group.powerstrip2_mp1
  # Turn on mp1 during day
  - id: CH004
    alias: Turn on mp1 during day
    trigger:
      platform: time
      at: '07:00:00'
    action:
    - service: homeassistant.turn_on
      entity_id: group.powerstrip2_mp1

switch:
  - platform: template
    switches:
      chargeur:
        friendly_name: "chargeur"
        value_template: "{{ is_state('timer.charge', 'active') }}"
        turn_on:
          - service: timer.start
            entity_id: timer.charge
          - service: homeassistant.turn_on
            entity_id: switch.prise3
        turn_off:
          - service: timer.cancel
            entity_id: timer.charge
          - service: homeassistant.turn_off
            entity_id: switch.prise3
      prise1:
        value_template: "{{ is_state('switch.prise1', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.prise1_on
        turn_off:
          service: script.turn_on
          entity_id: script.prise1_off
      prise2:
        value_template: "{{ is_state('switch.prise2', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.prise2_on
        turn_off:
          service: script.turn_on
          entity_id: script.prise2_off
      prise3:
        value_template: "{{ is_state('switch.prise3', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.prise3_on
        turn_off:
          service: script.turn_on
          entity_id: script.prise3_off
      prise4:
        value_template: "{{ is_state('switch.prise4', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.prise4_on
        turn_off:
          service: script.turn_on
          entity_id: script.prise4_off