timer:
  charge:
    duration: '04:00:00'

automation:
  # Turn on prise3
  - id: CH001
    alias: Turn on prise3
    trigger:
      platform: time
      at: "02:00:00"
    action:
    - service: timer.start
      entity_id: timer.charge
    - service: homeassistant.turn_on
      entity_id: switch.prise3
    - service: homeassistant.turn_on
      entity_id: switch.prise3
  # Turn off prise3 at the end of timer
  - id: CH002
    alias: Turn off prise3 when end timer
    trigger: 
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.charge
    action:
    - service: homeassistant.turn_off
      entity_id: switch.prise3
  # Turn off mp1 for bedtime
  - id: CH003
    alias: Turn off mp1 after we go to bed
    trigger:
      platform: time
      at: '23:59:00'
    action:
    - service: homeassistant.turn_off
      entity_id: group.powerstrip2_mp1
  # Turn on mp1 during day
  - id: CH004
    alias: Turn on mp1 during day
    trigger:
      platform: time
      at: '07:00:00'
    action:
    - service: homeassistant.turn_on
      entity_id: group.powerstrip2_mp1
