automation:
  # Presence Simulation Morning
  - id: SI001
    alias: Presence Simulation Morning On
    trigger:
      platform: time
      at: "06:30:00"
    condition:
      condition: state
      entity_id: input_select.home_mode
      state: 'Vacation'
    action:
    - delay: '00:{{ range(0,3) | random | int }}{{ range(0,9) | random | int }}:00'
    - service: homeassistant.turn_on
      entity_id:  light.chambre_evy
    - service: homeassistant.turn_on
      entity_id:  light.chambre_parent
  - id: SI002
    alias: Presence Simulation Morning Off
    trigger:
      platform: time
      at: "08:30:00"
    condition:
      condition: state
      entity_id: input_select.home_mode
      state: 'Vacation'
    action:
    - delay: '00:{{ range(0,3) | random | int }}{{ range(0,9) | random | int }}:00'
    - service: homeassistant.turn_off
      entity_id:  light.chambre_evy
    - service: homeassistant.turn_off
      entity_id:  light.chambre_parent
    # Presence Simulation Night
  - id: SI003
    alias: Presence Simulation Night On
    trigger:
      platform: time
      at: "22:30:00"
    condition:
      condition: state
      entity_id: input_select.home_mode
      state: 'Vacation'
    action:
    - delay: '00:{{ range(0,3) | random | int }}{{ range(0,9) | random | int }}:00'
    - service: homeassistant.turn_on
      entity_id:  light.chambre_evy
    - service: homeassistant.turn_on
      entity_id:  light.chambre_parent
  - id: SI004
    alias: Presence Simulation Night Off
    trigger:
      platform: time
      at: "23:30:00"
    condition:
      condition: state
      entity_id: input_select.home_mode
      state: 'Vacation'
    action:
    - delay: '00:{{ range(0,3) | random | int }}{{ range(0,9) | random | int }}:00'
    - service: homeassistant.turn_off
      entity_id:  light.chambre_evy
    - service: homeassistant.turn_off
      entity_id:  light.chambre_parent