# Activated when one of the sensors are opened and alarm is armed
- id: A009a
  alias: Windows Alarm
  trigger:
  - entity_id: group.windows
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm
# Activated when alarm is trigerred
- id: A009b
  alias: Send notification when alarm triggered
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: 'triggered'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomi_gw_mac
        ringtone_id: 1
        ringtone_vol: 100
    - service: notify.ju
      data_template:
        title: Alarm Triggered... 
        message: >         
          {% if states('binary_sensor.door_window_sensor_158d000232b0ad') == "on" %} 
          Fenetre_Parents
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000237d1e8') == "on" %} 
          Fenetre_Mia_Devant
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000238c840') == "on" %} 
            Fenetre_Mia_Laterale
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d00023295ce') == "on" %} 
            Fenetre_Evy
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000237d247') == "on" %} 
            Velux_Evy
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000238628c') == "on" %} 
            Fenetre_Chambre_Amis
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000237d1b8') == "on" %} 
            Fenetre_Upstairs
          {% endif %}
          {% if states('binary_sensor.door_window_sensor_158d000243645e') == "on" %} 
            Velux_Salle_de_bain
          {% endif %}
          <b>Opened</b>
    - service: homeassistant.turn_on
      entity_id: light.gateway_light_7811dcb8f98a
      data:
        brightness: 255
        rgb_color: [254,0,0]

- alias: 'Notify if door/window opened and no one is home'                                                                                                   
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home' 
  condition:
    - condition: state
      entity_id: group.doors, group.windows
      state: 'on'
  action:
    - service: notify.ju
      data_template:
        title: 'ALERT: Window or Door left opened while noone is home'
        message: >-
          {% for entity in trigger.to_state.attributes.entity_id %}
            {% if states(entity) == 'on' %}
              {{ state_attr(entity, 'friendly_name') }} is opened
            {% endif %}
          {% endfor %}

- alias: 'Notify if door/window opened for 60 minutes'                                                                                                   
  trigger:
    - platform: state
      entity_id: group.doors, group.windows
      to: 'on'
      for:
        hours: 0
        minutes: 60
        seconds: 0
  action:
    - service: notify.ju
      data_template:
        title: 'Window or Door Opened Too Long'
        message: >-
          {% for entity in trigger.to_state.attributes.entity_id %}
            {% if states(entity) == 'on' %}
              <p>{{ state_attr(entity, 'friendly_name') }} has been opened for 60 minutes</p><br>
            {% endif %}
          {% endfor %}


# Activated when alarm is armed
#- id: A009c
#  alias: indicator alarm is armed away
#  trigger:
#  - entity_id: alarm_control_panel.home_alarm
#    platform: state
#    from: 'disarmed'
#    to: 'pending'
#  action:
#  - service: script.alarm_armed
# Activated when alarm is disarmed
# - id: A009d
#   alias: restore alarm to initial state
#   trigger:
#   - entity_id: alarm_control_panel.home_alarm
#     platform: state
#     to: 'disarmed'
#   action:
#   - service: homeassistant.turn_on
#     entity_id: script.alarm_off
# Activated when smoke is detected
- id: A010
  alias: Send notification on fire alarm
  trigger:
  - entity_id: group.smoke
    platform: state
    from: 'off'
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: script.smoke_alarm
# Activated by parent switch left
- id: A012
  alias: Toggle Alarm
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d000237bae7
      click_type: single
  action:
  - service: homeassistant.toggle
    data:
      entity_id: switch.alarm_arm_away
# Activated when the door is opened
- id: A014a
  alias: Door Alert Open
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002c9c949 
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: notify.ju
    data_template:
      title: Main door opened ... 
      message: >         
        <b>door opened !</b>
# Activated when the door is closed
- id: A014a
  alias: Door Alert Closed
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002c9c949 
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: notify.ju
    data_template:
      title: Main door closed... 
      message: >         
        <b>door closed !</b>