---
sensor:
  - platform: avanza_stock
    stock: 745850
    name: avanza_sanofi
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
input_text:
  avanza_sanofi_min:
    icon: mdi:arrow-collapse-down
    name: Min Alert sanofi
  avanza_sanofi_max:
    icon: mdi:arrow-collapse-up
    name: Max Alert sanofi
  avanza_sanofi_bought:
    icon: mdi:arrow-collapse-right
    name: Bought Alert sanofi
automation:
  - id: avanza_sanofi
    alias: Avanza sanofi
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.avanza_sanofi') | float
          > states('input_text.avanza_sanofi_max') |float
          and states('input_text.avanza_sanofi_max') not in ['unknown', ''] }}
      - platform: template
        value_template: >
          {{ states('sensor.avanza_sanofi') | float
          < states('input_text.avanza_sanofi_min') | float
          and states('input_text.avanza_sanofi_min') not in ['unknown', ''] }}
    action:
      - service: script.notify
        data_template:
          type: Info
          message: >
            {% if states('sensor.avanza_sanofi') | float
            > states('input_text.avanza_sanofi_max') | float
            and states('input_text.avanza_sanofi_max') not in ['unknown', ''] %}
            "Stock alert: {{ state_attr('sensor.avanza_sanofi','name') }}:
            {{ states('sensor.avanza_sanofi') }}
            {{ state_attr('sensor.avanza_sanofi','currency') }}.
            Over threshold of {{ states('input_text.avanza_sanofi_max') }}"
            {% else %}
            "Stock alert: {{ state_attr('sensor.avanza_sanofi','name') }}:
            {{ states('sensor.avanza_sanofi') }}
            {{ state_attr('sensor.avanza_sanofi','currency') }}.
            Under threshold of {{ states('input_text.avanza_sanofi_min') }}"
            {% endif %}